In [49]:
import pandas as pd

In [50]:
chunk1 = pd.read_csv("chunk1.csv")
chunk2 = pd.read_csv("chunk2.csv")
chunk3 = pd.read_csv("chunk3.csv")

In [51]:
food_atlas = pd.concat([chunk1, chunk2, chunk3])
food_atlas.head()

,CensusTract,State,County,Urban,Pop2010,OHU2010,GroupQuartersFlag,NUMGQTRS,PCTGQTRS,LILATracts_1And10,...,TractSeniors,TractWhite,TractBlack,TractAsian,TractNHOPI,TractAIAN,TractOMultir,TractHispanic,TractHUNV,TractSNAP
0,1001020100,Alabama,Autauga County,1,1912,693,0,0.0,0.00,0,...,221.0,1622.0,217.0,14.0,0.0,14.0,45.0,44.0,6.0,102.0
1,1001020200,Alabama,Autauga County,1,2170,743,0,181.0,8.34,1,...,214.0,888.0,1217.0,5.0,0.0,5.0,55.0,75.0,89.0,156.0
2,1001020300,Alabama,Autauga County,1,3373,1256,0,0.0,0.00,0,...,439.0,2576.0,647.0,17.0,5.0,11.0,117.0,87.0,99.0,172.0
3,1001020400,Alabama,Autauga County,1,4386,1722,0,0.0,0.00,0,...,904.0,4086.0,193.0,18.0,4.0,11.0,74.0,85.0,21.0,98.0
4,1001020500,Alabama,Autauga County,1,10766,4082,0,181.0,1.68,0,...,1126.0,8666.0,1437.0,296.0,9.0,48.0,310.0,355.0,230.0,339.0

In [52]:
x = pd.DataFrame(food_atlas.isna().sum())
x

                          0
CensusTract               0
State                     0
County                    0
Urban                     0
Pop2010                   0
OHU2010                   0
GroupQuartersFlag         0
NUMGQTRS                 25
PCTGQTRS                 25
LILATracts_1And10         0
LILATracts_halfAnd10      0
LILATracts_1And20         0
LILATracts_Vehicle        0
HUNVFlag                  0
LowIncomeTracts           0
PovertyRate               3
MedianFamilyIncome      748
LA1and10                  0
LAhalfand10               0
LA1and20                  0
LATracts_half             0
LATracts1                 0
LATracts10                0
LATracts20                0
LATractsVehicle_20        0
LAPOP1_10             29957
LAPOP05_10            14540
LAPOP1_20             35914
LALOWI1_10            29957
LALOWI05_10           14540
LALOWI1_20            35914
lapophalf              4568
lapophalfshare         4568
lalowihalf             4568
lalowihalfshare        4568
lakidshalf             4568
lakidshalfshare        4568
laseniorshalf          4568
laseniorshalfshare     4568
lawhitehalf            4568
lawhitehalfshare       4568
lablackhalf            4568
lablackhalfshare       4568
laasianhalf            4568
laasianhalfshare       4568
lanhopihalf            4568
lanhopihalfshare       4568
laaianhalf             4568
laaianhalfshare        4568
laomultirhalf          4568
laomultirhalfshare     4568
lahisphalf             4568
lahisphalfshare        4568
lahunvhalf             4568
lahunvhalfshare        4562
lasnaphalf             4568
lasnaphalfshare        4562
lapop1                19989
lapop1share           19989
lalowi1               19989
lalowi1share          19989
lakids1               19989
lakids1share          19989
laseniors1            19989
laseniors1share       19989
lawhite1              19989
lawhite1share         19989
lablack1              19989
lablack1share         19989
laasian1              19989
laasian1share         19989
lanhopi1              19989
lanhopi1share         19989
laaian1               19989
laaian1share          19989
laomultir1            19989
laomultir1share       19989
lahisp1               19989
lahisp1share          19989
lahunv1               19989
lahunv1share          19966
lasnap1               19989
lasnap1share          19966
lapop10               64765
lapop10share          64765
lalowi10              64765
lalowi10share         64765
lakids10              64765
lakids10share         64765
laseniors10           64765
laseniors10share      64765
lawhite10             64765
lawhite10share        64765
lablack10             64765
lablack10share        64765
laasian10             64765
laasian10share        64765
lanhopi10             64765
lanhopi10share        64765
laaian10              64765
laaian10share         64765
laomultir10           64765
laomultir10share      64765
lahisp10              64765
lahisp10share         64765
lahunv10              64765
lahunv10share         64666
lasnap10              64765
lasnap10share         64666
lapop20               71025
lapop20share          71025
lalowi20              71025
lalowi20share         71025
lakids20              71025
lakids20share         71025
laseniors20           71025
laseniors20share      71025
lawhite20             71025
lawhite20share        71025
lablack20             71025
lablack20share        71025
laasian20             71025
laasian20share        71025
lanhopi20             71025
lanhopi20share        71025
laaian20              71025
laaian20share         71025
laomultir20           71025
laomultir20share      71025
lahisp20              71025
lahisp20share         71025
lahunv20              71025
lahunv20share         70920
lasnap20              71025
lasnap20share         70920
TractLOWI                 4
TractKids                 4
TractSeniors              4
TractWhite                4
TractBlack                4
TractAsian                4
TractNHOPI                4
TractAIAN                 4
TractOMultir              4
TractHispanic             4
TractHUNV                 4
TractSNAP                 4

In [53]:
pd.set_option('display.max_rows', len(x))

In [54]:
x

                          0
CensusTract               0
State                     0
County                    0
Urban                     0
Pop2010                   0
OHU2010                   0
GroupQuartersFlag         0
NUMGQTRS                 25
PCTGQTRS                 25
LILATracts_1And10         0
LILATracts_halfAnd10      0
LILATracts_1And20         0
LILATracts_Vehicle        0
HUNVFlag                  0
LowIncomeTracts           0
PovertyRate               3
MedianFamilyIncome      748
LA1and10                  0
LAhalfand10               0
LA1and20                  0
LATracts_half             0
LATracts1                 0
LATracts10                0
LATracts20                0
LATractsVehicle_20        0
LAPOP1_10             29957
LAPOP05_10            14540
LAPOP1_20             35914
LALOWI1_10            29957
LALOWI05_10           14540
LALOWI1_20            35914
lapophalf              4568
lapophalfshare         4568
lalowihalf             4568
lalowihalfshare        4568
lakidshalf             4568
lakidshalfshare        4568
laseniorshalf          4568
laseniorshalfshare     4568
lawhitehalf            4568
lawhitehalfshare       4568
lablackhalf            4568
lablackhalfshare       4568
laasianhalf            4568
laasianhalfshare       4568
lanhopihalf            4568
lanhopihalfshare       4568
laaianhalf             4568
laaianhalfshare        4568
laomultirhalf          4568
laomultirhalfshare     4568
lahisphalf             4568
lahisphalfshare        4568
lahunvhalf             4568
lahunvhalfshare        4562
lasnaphalf             4568
lasnaphalfshare        4562
lapop1                19989
lapop1share           19989
lalowi1               19989
lalowi1share          19989
lakids1               19989
lakids1share          19989
laseniors1            19989
laseniors1share       19989
lawhite1              19989
lawhite1share         19989
lablack1              19989
lablack1share         19989
laasian1              19989
laasian1share         19989
lanhopi1              19989
lanhopi1share         19989
laaian1               19989
laaian1share          19989
laomultir1            19989
laomultir1share       19989
lahisp1               19989
lahisp1share          19989
lahunv1               19989
lahunv1share          19966
lasnap1               19989
lasnap1share          19966
lapop10               64765
lapop10share          64765
lalowi10              64765
lalowi10share         64765
lakids10              64765
lakids10share         64765
laseniors10           64765
laseniors10share      64765
lawhite10             64765
lawhite10share        64765
lablack10             64765
lablack10share        64765
laasian10             64765
laasian10share        64765
lanhopi10             64765
lanhopi10share        64765
laaian10              64765
laaian10share         64765
laomultir10           64765
laomultir10share      64765
lahisp10              64765
lahisp10share         64765
lahunv10              64765
lahunv10share         64666
lasnap10              64765
lasnap10share         64666
lapop20               71025
lapop20share          71025
lalowi20              71025
lalowi20share         71025
lakids20              71025
lakids20share         71025
laseniors20           71025
laseniors20share      71025
lawhite20             71025
lawhite20share        71025
lablack20             71025
lablack20share        71025
laasian20             71025
laasian20share        71025
lanhopi20             71025
lanhopi20share        71025
laaian20              71025
laaian20share         71025
laomultir20           71025
laomultir20share      71025
lahisp20              71025
lahisp20share         71025
lahunv20              71025
lahunv20share         70920
lasnap20              71025
lasnap20share         70920
TractLOWI                 4
TractKids                 4
TractSeniors              4
TractWhite                4
TractBlack                4
TractAsian                4
TractNHOPI                4
TractAIAN                 4
TractOMultir              4
TractHispanic             4
TractHUNV                 4
TractSNAP                 4

In [55]:
meal_gap = pd.read_csv("Map the Meal Gap.csv")

In [56]:
meal_gap.head()

,FIPS,State,"County, State",Year,Overall Food Insecurity Rate,# of Food Insecure Persons Overall,Food Insecurity Rate among Black Persons (all ethnicities),Food Insecurity Rate among Hispanic Persons (any race),"Food Insecurity Rate among White, non-Hispanic Persons",SNAP Threshold,...,% food insecure children in HH w/ HH incomes below 185 FPL,% food insecure children in HH w/ HH incomes above 185 FPL,Cost Per Meal,Weighted weekly $ needed by FI,Weighted Annual Food Budget Shortfall,Rural-Urban Continuum Code (2013),Rural-Urban Continuum Code (2023),Census Region,Census Division,FNS Region
0,1001,AL,"Autauga County, Alabama",2019,15.7%,"8,670",26%,NaN,12%,130%,...,69%,31%,$3.00,$16.88,"$4,439,000",2.0,NaN,South,East South Central,Southeast
1,1001,AL,"Autauga County, Alabama",2020,14.5%,"8,070",25%,NaN,9%,130%,...,71%,29%,$3.22,$17.09,"$4,184,000",2.0,NaN,South,East South Central,Southeast
2,1001,AL,"Autauga County, Alabama",2021,13.3%,"7,770",23%,NaN,9%,130%,...,68%,32%,$3.60,$20.99,"$4,947,000",2.0,NaN,South,East South Central,Southeast
3,1001,AL,"Autauga County, Alabama",2022,15.1%,"8,860",23%,NaN,11%,130%,...,68%,32%,$4.01,$24.86,"$6,680,000",2.0,2.0,South,East South Central,Southeast
4,1001,AL,"Autauga County, Alabama",2023,15.1%,"8,970",24%,NaN,12%,130%,...,66%,34%,$3.64,$22.72,"$6,183,000",2.0,2.0,South,East South Central,Southeast

In [57]:
meal_gap_2019 = meal_gap[meal_gap.Year == 2019]
meal_gap_2019.head()

,FIPS,State,"County, State",Year,Overall Food Insecurity Rate,# of Food Insecure Persons Overall,Food Insecurity Rate among Black Persons (all ethnicities),Food Insecurity Rate among Hispanic Persons (any race),"Food Insecurity Rate among White, non-Hispanic Persons",SNAP Threshold,...,% food insecure children in HH w/ HH incomes below 185 FPL,% food insecure children in HH w/ HH incomes above 185 FPL,Cost Per Meal,Weighted weekly $ needed by FI,Weighted Annual Food Budget Shortfall,Rural-Urban Continuum Code (2013),Rural-Urban Continuum Code (2023),Census Region,Census Division,FNS Region
0,1001,AL,"Autauga County, Alabama",2019,15.7%,"8,670",26%,NaN,12%,130%,...,69%,31%,$3.00,$16.88,"$4,439,000",2.0,NaN,South,East South Central,Southeast
5,1003,AL,"Baldwin County, Alabama",2019,13.4%,"28,590",26%,10%,11%,130%,...,79%,21%,$3.66,$20.63,"$17,895,000",3.0,NaN,South,East South Central,Southeast
10,1005,AL,"Barbour County, Alabama",2019,20.7%,"5,250",34%,NaN,14%,130%,...,72%,28%,$3.11,$17.51,"$2,788,000",6.0,NaN,South,East South Central,Southeast
15,1007,AL,"Bibb County, Alabama",2019,16.3%,"3,680",28%,NaN,14%,130%,...,89%,11%,$2.96,$16.68,"$1,861,000",1.0,NaN,South,East South Central,Southeast
20,1009,AL,"Blount County, Alabama",2019,14.5%,"8,380",14%,11%,12%,130%,...,100%,0%,$3.04,$17.14,"$4,357,000",1.0,NaN,South,East South Central,Southeast

In [58]:
meal_gap_2019.shape

(3142, 24)

In [59]:
food_atlas.groupby(['State', 'County']).agg('count')

                           CensusTract  Urban  Pop2010  OHU2010  \
State   County
Alabama Autauga County              12     12       12       12
        Baldwin County              31     31       31       31
        Barbour County               9      9        9        9
        Bibb County                  4      4        4        4
        Blount County                9      9        9        9
...                                ...    ...      ...      ...
Wyoming Sweetwater County           12     12       12       12
        Teton County                 4      4        4        4
        Uinta County                 3      3        3        3
        Washakie County              3      3        3        3
        Weston County                2      2        2        2

                           GroupQuartersFlag  NUMGQTRS  PCTGQTRS  \
State   County
Alabama Autauga County                    12        12        12
        Baldwin County                    31        31        31
        Barbour County                     9         9         9
        Bibb County                        4         4         4
        Blount County                      9         9         9
...                                      ...       ...       ...
Wyoming Sweetwater County                 12        12        12
        Teton County                       4         4         4
        Uinta County                       3         3         3
        Washakie County                    3         3         3
        Weston County                      2         2         2

                           LILATracts_1And10  LILATracts_halfAnd10  \
State   County
Alabama Autauga County                    12                    12
        Baldwin County                    31                    31
        Barbour County                     9                     9
        Bibb County                        4                     4
        Blount County                      9                     9
...                                      ...                   ...
Wyoming Sweetwater County                 12                    12
        Teton County                       4                     4
        Uinta County                       3                     3
        Washakie County                    3                     3
        Weston County                      2                     2

                           LILATracts_1And20  ...  TractSeniors  TractWhite  \
State   County                                ...
Alabama Autauga County                    12  ...            12          12
        Baldwin County                    31  ...            31          31
        Barbour County                     9  ...             9           9
        Bibb County                        4  ...             4           4
        Blount County                      9  ...             9           9
...                                      ...  ...           ...         ...
Wyoming Sweetwater County                 12  ...            12          12
        Teton County                       4  ...             4           4
        Uinta County                       3  ...             3           3
        Washakie County                    3  ...             3           3
        Weston County                      2  ...             2           2

                           TractBlack  TractAsian  TractNHOPI  TractAIAN  \
State   County
Alabama Autauga County             12          12          12         12
        Baldwin County             31          31          31         31
        Barbour County              9           9           9          9
        Bibb County                 4           4           4          4
        Blount County               9           9           9          9
...                               ...         ...         ...        ...
Wyoming Sweetwater County          12          12          12         12
        Teton County                4           4           4          4
        Uinta County                3           3           3          3
        Washakie County             3           3           3          3
        Weston County               2           2           2          2

                           TractOMultir  TractHispanic  TractHUNV  TractSNAP
State   County
Alabama Autauga County               12             12         12         12
        Baldwin County               31             31         31         31
        Barbour County                9              9          9          9
        Bibb County                   4              4          4          4
        Blount County                 9              9          9          9
...                                 ...            ...        ...        ...
Wyoming Sweetwater County            12             12         12         12
        Teton County                  4              4          4          4
        Uinta County                  3              3          3          3
        Washakie County               3              3          3          3
        Weston County                 2              2          2          2

[3142 rows x 145 columns]

In [60]:
food_atlas['County, State'] = food_atlas['County'].astype(str) + ', ' +  food_atlas['State'].astype(str)

In [61]:
food_atlas.head()

,CensusTract,State,County,Urban,Pop2010,OHU2010,GroupQuartersFlag,NUMGQTRS,PCTGQTRS,LILATracts_1And10,...,TractWhite,TractBlack,TractAsian,TractNHOPI,TractAIAN,TractOMultir,TractHispanic,TractHUNV,TractSNAP,"County, State"
0,1001020100,Alabama,Autauga County,1,1912,693,0,0.0,0.00,0,...,1622.0,217.0,14.0,0.0,14.0,45.0,44.0,6.0,102.0,"Autauga County, Alabama"
1,1001020200,Alabama,Autauga County,1,2170,743,0,181.0,8.34,1,...,888.0,1217.0,5.0,0.0,5.0,55.0,75.0,89.0,156.0,"Autauga County, Alabama"
2,1001020300,Alabama,Autauga County,1,3373,1256,0,0.0,0.00,0,...,2576.0,647.0,17.0,5.0,11.0,117.0,87.0,99.0,172.0,"Autauga County, Alabama"
3,1001020400,Alabama,Autauga County,1,4386,1722,0,0.0,0.00,0,...,4086.0,193.0,18.0,4.0,11.0,74.0,85.0,21.0,98.0,"Autauga County, Alabama"
4,1001020500,Alabama,Autauga County,1,10766,4082,0,181.0,1.68,0,...,8666.0,1437.0,296.0,9.0,48.0,310.0,355.0,230.0,339.0,"Autauga County, Alabama"

In [62]:
meal_gap_2019.shape

(3142, 24)

In [63]:
food_atlas.shape

(72531, 148)

In [64]:
meal_gap_2019.shape[1] + food_atlas.shape[1]

172

In [65]:
merged_data = food_atlas.merge(meal_gap_2019, on='County, State', how='left')
merged_data

,CensusTract,State_x,County,Urban,Pop2010,OHU2010,GroupQuartersFlag,NUMGQTRS,PCTGQTRS,LILATracts_1And10,...,% food insecure children in HH w/ HH incomes below 185 FPL,% food insecure children in HH w/ HH incomes above 185 FPL,Cost Per Meal,Weighted weekly $ needed by FI,Weighted Annual Food Budget Shortfall,Rural-Urban Continuum Code (2013),Rural-Urban Continuum Code (2023),Census Region,Census Division,FNS Region
0,1001020100,Alabama,Autauga County,1,1912,693,0,0.0,0.00,0,...,69%,31%,$3.00,$16.88,"$4,439,000",2.0,NaN,South,East South Central,Southeast
1,1001020200,Alabama,Autauga County,1,2170,743,0,181.0,8.34,1,...,69%,31%,$3.00,$16.88,"$4,439,000",2.0,NaN,South,East South Central,Southeast
2,1001020300,Alabama,Autauga County,1,3373,1256,0,0.0,0.00,0,...,69%,31%,$3.00,$16.88,"$4,439,000",2.0,NaN,South,East South Central,Southeast
3,1001020400,Alabama,Autauga County,1,4386,1722,0,0.0,0.00,0,...,69%,31%,$3.00,$16.88,"$4,439,000",2.0,NaN,South,East South Central,Southeast
4,1001020500,Alabama,Autauga County,1,10766,4082,0,181.0,1.68,0,...,69%,31%,$3.00,$16.88,"$4,439,000",2.0,NaN,South,East South Central,Southeast
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72526,56043000200,Wyoming,Washakie County,0,3326,1317,0,57.0,1.71,0,...,76%,24%,$3.24,$18.25,"$515,000",7.0,NaN,West,Mountain,Mountain Plains
72527,56043000301,Wyoming,Washakie County,1,2665,1154,0,10.0,0.38,0,...,76%,24%,$3.24,$18.25,"$515,000",7.0,NaN,West,Mountain,Mountain Plains
72528,56043000302,Wyoming,Washakie County,1,2542,1021,0,73.0,2.87,0,...,76%,24%,$3.24,$18.25,"$515,000",7.0,NaN,West,Mountain,Mountain Plains
72529,56045951100,Wyoming,Weston County,0,3314,1322,0,252.0,7.60,0,...,62%,38%,$3.21,$18.07,"$471,000",7.0,NaN,West,Mountain,Mountain Plains
72530,56045951300,Wyoming,Weston County,1,3894,1699,0,61.0,1.57,0,...,62%,38%,$3.21,$18.07,"$471,000",7.0,NaN,West,Mountain,Mountain Plains

In [66]:
list(merged_data.columns)

['CensusTract',
 'State_x',
 'County',
 'Urban',
 'Pop2010',
 'OHU2010',
 'GroupQuartersFlag',
 'NUMGQTRS',
 'PCTGQTRS',
 'LILATracts_1And10',
 'LILATracts_halfAnd10',
 'LILATracts_1And20',
 'LILATracts_Vehicle',
 'HUNVFlag',
 'LowIncomeTracts',
 'PovertyRate',
 'MedianFamilyIncome',
 'LA1and10',
 'LAhalfand10',
 'LA1and20',
 'LATracts_half',
 'LATracts1',
 'LATracts10',
 'LATracts20',
 'LATractsVehicle_20',
 'LAPOP1_10',
 'LAPOP05_10',
 'LAPOP1_20',
 'LALOWI1_10',
 'LALOWI05_10',
 'LALOWI1_20',
 'lapophalf',
 'lapophalfshare',
 'lalowihalf',
 'lalowihalfshare',
 'lakidshalf',
 'lakidshalfshare',
 'laseniorshalf',
 'laseniorshalfshare',
 'lawhitehalf',
 'lawhitehalfshare',
 'lablackhalf',
 'lablackhalfshare',
 'laasianhalf',
 'laasianhalfshare',
 'lanhopihalf',
 'lanhopihalfshare',
 'laaianhalf',
 'laaianhalfshare',
 'laomultirhalf',
 'laomultirhalfshare',
 'lahisphalf',
 'lahisphalfshare',
 'lahunvhalf',
 'lahunvhalfshare',
 'lasnaphalf',
 'lasnaphalfshare',
 'lapop1',
 'lapop1share',
 'lalowi1',
 'lalowi1share',
 'lakids1',
 'lakids1share',
 'laseniors1',
 'laseniors1share',
 'lawhite1',
 'lawhite1share',
 'lablack1',
 'lablack1share',
 'laasian1',
 'laasian1share',
 'lanhopi1',
 'lanhopi1share',
 'laaian1',
 'laaian1share',
 'laomultir1',
 'laomultir1share',
 'lahisp1',
 'lahisp1share',
 'lahunv1',
 'lahunv1share',
 'lasnap1',
 'lasnap1share',
 'lapop10',
 'lapop10share',
 'lalowi10',
 'lalowi10share',
 'lakids10',
 'lakids10share',
 'laseniors10',
 'laseniors10share',
 'lawhite10',
 'lawhite10share',
 'lablack10',
 'lablack10share',
 'laasian10',
 'laasian10share',
 'lanhopi10',
 'lanhopi10share',
 'laaian10',
 'laaian10share',
 'laomultir10',
 'laomultir10share',
 'lahisp10',
 'lahisp10share',
 'lahunv10',
 'lahunv10share',
 'lasnap10',
 'lasnap10share',
 'lapop20',
 'lapop20share',
 'lalowi20',
 'lalowi20share',
 'lakids20',
 'lakids20share',
 'laseniors20',
 'laseniors20share',
 'lawhite20',
 'lawhite20share',
 'lablack20',
 'lablack20share',
 'laasian20',
 'laasian20share',
 'lanhopi20',
 'lanhopi20share',
 'laaian20',
 'laaian20share',
 'laomultir20',
 'laomultir20share',
 'lahisp20',
 'lahisp20share',
 'lahunv20',
 'lahunv20share',
 'lasnap20',
 'lasnap20share',
 'TractLOWI',
 'TractKids',
 'TractSeniors',
 'TractWhite',
 'TractBlack',
 'TractAsian',
 'TractNHOPI',
 'TractAIAN',
 'TractOMultir',
 'TractHispanic',
 'TractHUNV',
 'TractSNAP',
 'County, State',
 'FIPS',
 'State_y',
 'Year',
 'Overall Food Insecurity Rate',
 '# of Food Insecure Persons Overall',
 'Food Insecurity Rate among Black Persons (all ethnicities)',
 'Food Insecurity Rate among Hispanic Persons (any race)',
 'Food Insecurity Rate among White, non-Hispanic Persons',
 'SNAP Threshold',
 '% FI ≤ SNAP Threshold',
 '% FI > SNAP Threshold',
 'Child Food Insecurity Rate',
 '# of Food Insecure Children',
 '% food insecure children in HH w/ HH incomes below 185 FPL',
 '% food insecure children in HH w/ HH incomes above 185 FPL',
 'Cost Per Meal',
 'Weighted weekly $ needed by FI',
 'Weighted Annual Food Budget Shortfall',
 'Rural-Urban Continuum Code (2013)',
 'Rural-Urban Continuum Code (2023)',
 'Census Region',
 'Census Division',
 'FNS Region']

In [42]:
merged_data = merged_data.drop(['State_y', 'Year'], axis=1)

In [67]:
merged_data.shape

(72531, 171)

In [46]:
merged_data_columns = ['censusTract',
               'State',
               'County',
               'isUrban',
               'Population',
               'housingUnit',
               'isGroupQuarter67%',
               'numGroupQuarter',
               'pctGroupQuarter',
               'isLILA_1_10',
               'isLILA_half_10',
               'isLILA_1_20,'
               'isLILA_Vehicle',
               'isLowVehicleAccess',
               'isLowIncome',
               'povertyRate',
               'medianFamilyIncome',
               'isLA_1_10',
               'isLA_half_10',
               'isLA_1_20',
               'isLA_half',
               'isLA_1',
               'isLA_10',
               'isLA_20',
               'isLowVehicleAccessOr20Miles',
               'numLA_1_10',
               'numLA_half_10',
               'numLA_1_20',
               'numLILA_1_10',
               'numLILA_half_10',
               'numLILA_1_20',
               'numLA_half',
               'pctLA_half',
               'numLILA_half',
               'pctLILA_half',
               'numLAKids_half',
               'pctLAKids_half',
               'numLASeniors_half',
               'pctLASeniors_half',
               'numLAWhite_half',
               'pctLAWhite_half',
               'numLABlack_half',
               'pctLABlack_half',
               'numLAAsian_half',
               'pctLAAsian_half',
               'numLAnhopi_half',
               'pctLAnhopi_half',
               'numLANative_half',
               'pctLANative_half',
               'numLAOtherRace_half',
               'pctLAOtherRace_half',
               'numLALatine_half',
               'pctLALatine_half',
               'numLAHousingUnitNoVehicle_half',
               'pctLAHousingUnitNoVehicle_half',
               'numLAHousingUnitSNAP_half',
               'pctLAHousingUnitSNAP_half',
               'numLA_1',
               'pctLA_1',
               'numLILA_1',
               'pctLILA_1',
               'numLAKids_1',
               'pctLAKids_1',
               'numLASeniors_1',
               'pctLASeniors_1',
               'numLAWhite_1',
               'pctLAWhite_1',
               'numLABlack_1',
               'pctLABlack_1',
               'numLAAsian_1',
               'pctLAAsian_1',
               'numLAnhopi_1',
               'pctLAnhopi_1',
               'numLANative_1',
               'pctLANative_1',
               'numLAOtherRace_1',
               'pctLAOtherRace_1',
               'numLALatine_1',
               'pctLALatine_1',
               'numLAHousingUnitNoVehicle_1',
               'pctLAHousingUnitNoVehicle_1',
               'numLAHousingUnitSNAP_1',
               'pctLAHousingUnitSNAP_1',
               'numLA_10',
               'pctLA_10',
               'numLILA_10',
               'pctLILA_10',
               'numLAKids_10',
               'pctLAKids_10',
               'numLASeniors_10',
               'pctLASeniors_10',
               'numLAWhite_10',
               'pctLAWhite_10',
               'numLABlack_10',
               'pctLABlack_10',
               'numLAAsian_10',
               'pctLAAsian_10',
               'numLAnhopi_10',
               'pctLAnhopi_10',
               'numLANative_10',
               'pctLANative_10',
               'numLAOtherRace_10',
               'pctLAOtherRace_10',
               'numLALatine_10',
               'pctLALatine_10',
               'numLAHousingUnitNoVehicle_10',
               'pctLAHousingUnitNoVehicle_10',
               'numLAHousingUnitSNAP_10',
               'pctLAHousingUnitSNAP_10',
               'numLA_20',
               'pctLA_20',
               'numLILA_20',
               'pctLILA_20',
               'numLAKids_20',
               'pctLAKids_20',
               'numLASeniors_20',
               'pctLASeniors_20',
               'numLAWhite_20',
               'pctLAWhite_20',
               'numLABlack_20',
               'pctLABlack_20',
               'numLAAsian_20',
               'pctLAAsian_20',
               'numLAnhopi_20',
               'pctLAnhopi_20',
               'numLANative_20',
               'pctLANative_20',
               'numLAOtherRace_20',
               'pctLAOtherRace_20',
               'numLALatine_20',
               'pctLALatine_20',
               'numLAHousingUnitNoVehicle_20',
               'pctLAHousingUnitNoVehicle_20',
               'numLAHousingUnitSNAP_20',
               'pctLAHousingUnitNAP_20',
               'numLI',
               'numKids',
               'numSeniors',
               'numWhite',
               'numBlack',
               'numAsian',
               'numNHOPI',
               'numNative',
               'numOtherRace',
               'numLatine',
               'numHousingUnitNoVehicle',
               'numHousingUnitSNAP']

In [68]:
len(merged_data_columns)

146