In [511]:
import pandas as pd

# Reading in data

In [512]:
chunk1 = pd.read_csv("chunk1.csv")
chunk2 = pd.read_csv("chunk2.csv")
chunk3 = pd.read_csv("chunk3.csv")

In [513]:
food_atlas = pd.concat([chunk1, chunk2, chunk3])
food_atlas.head()

,CensusTract,State,County,Urban,Pop2010,OHU2010,GroupQuartersFlag,NUMGQTRS,PCTGQTRS,LILATracts_1And10,...,TractSeniors,TractWhite,TractBlack,TractAsian,TractNHOPI,TractAIAN,TractOMultir,TractHispanic,TractHUNV,TractSNAP
0,1001020100,Alabama,Autauga County,1,1912,693,0,0.0,0.00,0,...,221.0,1622.0,217.0,14.0,0.0,14.0,45.0,44.0,6.0,102.0
1,1001020200,Alabama,Autauga County,1,2170,743,0,181.0,8.34,1,...,214.0,888.0,1217.0,5.0,0.0,5.0,55.0,75.0,89.0,156.0
2,1001020300,Alabama,Autauga County,1,3373,1256,0,0.0,0.00,0,...,439.0,2576.0,647.0,17.0,5.0,11.0,117.0,87.0,99.0,172.0
3,1001020400,Alabama,Autauga County,1,4386,1722,0,0.0,0.00,0,...,904.0,4086.0,193.0,18.0,4.0,11.0,74.0,85.0,21.0,98.0
4,1001020500,Alabama,Autauga County,1,10766,4082,0,181.0,1.68,0,...,1126.0,8666.0,1437.0,296.0,9.0,48.0,310.0,355.0,230.0,339.0

In [514]:
meal_gap = pd.read_csv("Map the Meal Gap.csv")

In [515]:
meal_gap.head()

,FIPS,State,"County, State",Year,Overall Food Insecurity Rate,# of Food Insecure Persons Overall,Food Insecurity Rate among Black Persons (all ethnicities),Food Insecurity Rate among Hispanic Persons (any race),"Food Insecurity Rate among White, non-Hispanic Persons",SNAP Threshold,...,% food insecure children in HH w/ HH incomes below 185 FPL,% food insecure children in HH w/ HH incomes above 185 FPL,Cost Per Meal,Weighted weekly $ needed by FI,Weighted Annual Food Budget Shortfall,Rural-Urban Continuum Code (2013),Rural-Urban Continuum Code (2023),Census Region,Census Division,FNS Region
0,1001,AL,"Autauga County, Alabama",2019,15.7%,"8,670",26%,NaN,12%,130%,...,69%,31%,$3.00,$16.88,"$4,439,000",2.0,NaN,South,East South Central,Southeast
1,1001,AL,"Autauga County, Alabama",2020,14.5%,"8,070",25%,NaN,9%,130%,...,71%,29%,$3.22,$17.09,"$4,184,000",2.0,NaN,South,East South Central,Southeast
2,1001,AL,"Autauga County, Alabama",2021,13.3%,"7,770",23%,NaN,9%,130%,...,68%,32%,$3.60,$20.99,"$4,947,000",2.0,NaN,South,East South Central,Southeast
3,1001,AL,"Autauga County, Alabama",2022,15.1%,"8,860",23%,NaN,11%,130%,...,68%,32%,$4.01,$24.86,"$6,680,000",2.0,2.0,South,East South Central,Southeast
4,1001,AL,"Autauga County, Alabama",2023,15.1%,"8,970",24%,NaN,12%,130%,...,66%,34%,$3.64,$22.72,"$6,183,000",2.0,2.0,South,East South Central,Southeast

In [516]:
meal_gap_2019 = meal_gap[meal_gap.Year == 2019]
meal_gap_2019.head()

,FIPS,State,"County, State",Year,Overall Food Insecurity Rate,# of Food Insecure Persons Overall,Food Insecurity Rate among Black Persons (all ethnicities),Food Insecurity Rate among Hispanic Persons (any race),"Food Insecurity Rate among White, non-Hispanic Persons",SNAP Threshold,...,% food insecure children in HH w/ HH incomes below 185 FPL,% food insecure children in HH w/ HH incomes above 185 FPL,Cost Per Meal,Weighted weekly $ needed by FI,Weighted Annual Food Budget Shortfall,Rural-Urban Continuum Code (2013),Rural-Urban Continuum Code (2023),Census Region,Census Division,FNS Region
0,1001,AL,"Autauga County, Alabama",2019,15.7%,"8,670",26%,NaN,12%,130%,...,69%,31%,$3.00,$16.88,"$4,439,000",2.0,NaN,South,East South Central,Southeast
5,1003,AL,"Baldwin County, Alabama",2019,13.4%,"28,590",26%,10%,11%,130%,...,79%,21%,$3.66,$20.63,"$17,895,000",3.0,NaN,South,East South Central,Southeast
10,1005,AL,"Barbour County, Alabama",2019,20.7%,"5,250",34%,NaN,14%,130%,...,72%,28%,$3.11,$17.51,"$2,788,000",6.0,NaN,South,East South Central,Southeast
15,1007,AL,"Bibb County, Alabama",2019,16.3%,"3,680",28%,NaN,14%,130%,...,89%,11%,$2.96,$16.68,"$1,861,000",1.0,NaN,South,East South Central,Southeast
20,1009,AL,"Blount County, Alabama",2019,14.5%,"8,380",14%,11%,12%,130%,...,100%,0%,$3.04,$17.14,"$4,357,000",1.0,NaN,South,East South Central,Southeast

In [517]:
meal_gap_2019.shape

(3142, 24)

# Cleaning food atlas dataset

In [519]:
food_atlas.shape

(72531, 147)

In [520]:
food_atlas['County, State'] = food_atlas['County'].astype(str) + ', ' +  food_atlas['State'].astype(str)

In [521]:
food_atlas = food_atlas.drop(['County', 'State'], axis=1)

In [522]:
food_atlas.shape

(72531, 146)

In [523]:
food_atlas_columns = ['censusTract',
               'County, State',
               #'State',
               #'County',
               'isUrban',
               'Population',
               'housingUnit',
               'isGroupQuarter67%',
               'numGroupQuarter',
               'pctGroupQuarter',
               'isLILA_1_10',
               'isLILA_half_10',
               'isLILA_1_20,',
               'isLILA_Vehicle',
               'isLowVehicleAccess',
               'isLowIncome',
               'povertyRate',
               'medianFamilyIncome',
               'isLA_1_10',
               'isLA_half_10',
               'isLA_1_20',
               'isLA_half',
               'isLA_1',
               'isLA_10',
               'isLA_20',
               'isLowVehicleAccessOr20Miles',
               'numLA_1_10',
               'numLA_half_10',
               'numLA_1_20',
               'numLILA_1_10',
               'numLILA_half_10',
               'numLILA_1_20',
               'numLA_half',
               'pctLA_half',
               'numLILA_half',
               'pctLILA_half',
               'numLAKids_half',
               'pctLAKids_half',
               'numLASeniors_half',
               'pctLASeniors_half',
               'numLAWhite_half',
               'pctLAWhite_half',
               'numLABlack_half',
               'pctLABlack_half',
               'numLAAsian_half',
               'pctLAAsian_half',
               'numLAnhopi_half',
               'pctLAnhopi_half',
               'numLANative_half',
               'pctLANative_half',
               'numLAOtherRace_half',
               'pctLAOtherRace_half',
               'numLALatine_half',
               'pctLALatine_half',
               'numLAHousingUnitNoVehicle_half',
               'pctLAHousingUnitNoVehicle_half',
               'numLAHousingUnitSNAP_half',
               'pctLAHousingUnitSNAP_half',
               'numLA_1',
               'pctLA_1',
               'numLILA_1',
               'pctLILA_1',
               'numLAKids_1',
               'pctLAKids_1',
               'numLASeniors_1',
               'pctLASeniors_1',
               'numLAWhite_1',
               'pctLAWhite_1',
               'numLABlack_1',
               'pctLABlack_1',
               'numLAAsian_1',
               'pctLAAsian_1',
               'numLAnhopi_1',
               'pctLAnhopi_1',
               'numLANative_1',
               'pctLANative_1',
               'numLAOtherRace_1',
               'pctLAOtherRace_1',
               'numLALatine_1',
               'pctLALatine_1',
               'numLAHousingUnitNoVehicle_1',
               'pctLAHousingUnitNoVehicle_1',
               'numLAHousingUnitSNAP_1',
               'pctLAHousingUnitSNAP_1',
               'numLA_10',
               'pctLA_10',
               'numLILA_10',
               'pctLILA_10',
               'numLAKids_10',
               'pctLAKids_10',
               'numLASeniors_10',
               'pctLASeniors_10',
               'numLAWhite_10',
               'pctLAWhite_10',
               'numLABlack_10',
               'pctLABlack_10',
               'numLAAsian_10',
               'pctLAAsian_10',
               'numLAnhopi_10',
               'pctLAnhopi_10',
               'numLANative_10',
               'pctLANative_10',
               'numLAOtherRace_10',
               'pctLAOtherRace_10',
               'numLALatine_10',
               'pctLALatine_10',
               'numLAHousingUnitNoVehicle_10',
               'pctLAHousingUnitNoVehicle_10',
               'numLAHousingUnitSNAP_10',
               'pctLAHousingUnitSNAP_10',
               'numLA_20',
               'pctLA_20',
               'numLILA_20',
               'pctLILA_20',
               'numLAKids_20',
               'pctLAKids_20',
               'numLASeniors_20',
               'pctLASeniors_20',
               'numLAWhite_20',
               'pctLAWhite_20',
               'numLABlack_20',
               'pctLABlack_20',
               'numLAAsian_20',
               'pctLAAsian_20',
               'numLAnhopi_20',
               'pctLAnhopi_20',
               'numLANative_20',
               'pctLANative_20',
               'numLAOtherRace_20',
               'pctLAOtherRace_20',
               'numLALatine_20',
               'pctLALatine_20',
               'numLAHousingUnitNoVehicle_20',
               'pctLAHousingUnitNoVehicle_20',
               'numLAHousingUnitSNAP_20',
               'pctLAHousingUnitNAP_20',
               'numLI',
               'numKids',
               'numSeniors',
               'numWhite',
               'numBlack',
               'numAsian',
               'numNHOPI',
               'numNative',
               'numOtherRace',
               'numLatine',
               'numHousingUnitNoVehicle',
               'numHousingUnitSNAP']

In [524]:
len(food_atlas_columns)

146

In [525]:
food_atlas.head()

,CensusTract,Urban,Pop2010,OHU2010,GroupQuartersFlag,NUMGQTRS,PCTGQTRS,LILATracts_1And10,LILATracts_halfAnd10,LILATracts_1And20,...,TractWhite,TractBlack,TractAsian,TractNHOPI,TractAIAN,TractOMultir,TractHispanic,TractHUNV,TractSNAP,"County, State"
0,1001020100,1,1912,693,0,0.0,0.00,0,0,0,...,1622.0,217.0,14.0,0.0,14.0,45.0,44.0,6.0,102.0,"Autauga County, Alabama"
1,1001020200,1,2170,743,0,181.0,8.34,1,1,1,...,888.0,1217.0,5.0,0.0,5.0,55.0,75.0,89.0,156.0,"Autauga County, Alabama"
2,1001020300,1,3373,1256,0,0.0,0.00,0,0,0,...,2576.0,647.0,17.0,5.0,11.0,117.0,87.0,99.0,172.0,"Autauga County, Alabama"
3,1001020400,1,4386,1722,0,0.0,0.00,0,0,0,...,4086.0,193.0,18.0,4.0,11.0,74.0,85.0,21.0,98.0,"Autauga County, Alabama"
4,1001020500,1,10766,4082,0,181.0,1.68,0,0,0,...,8666.0,1437.0,296.0,9.0,48.0,310.0,355.0,230.0,339.0,"Autauga County, Alabama"

In [526]:
reindex = [0, -1] + list(range(1, 145))
food_atlas = food_atlas.iloc[:,reindex]

In [527]:
food_atlas.shape

(72531, 146)

In [528]:
food_atlas = food_atlas.set_axis(food_atlas_columns, axis=1)
food_atlas.head()

,censusTract,"County, State",isUrban,Population,housingUnit,isGroupQuarter67%,numGroupQuarter,pctGroupQuarter,isLILA_1_10,isLILA_half_10,...,numSeniors,numWhite,numBlack,numAsian,numNHOPI,numNative,numOtherRace,numLatine,numHousingUnitNoVehicle,numHousingUnitSNAP
0,1001020100,"Autauga County, Alabama",1,1912,693,0,0.0,0.00,0,0,...,221.0,1622.0,217.0,14.0,0.0,14.0,45.0,44.0,6.0,102.0
1,1001020200,"Autauga County, Alabama",1,2170,743,0,181.0,8.34,1,1,...,214.0,888.0,1217.0,5.0,0.0,5.0,55.0,75.0,89.0,156.0
2,1001020300,"Autauga County, Alabama",1,3373,1256,0,0.0,0.00,0,0,...,439.0,2576.0,647.0,17.0,5.0,11.0,117.0,87.0,99.0,172.0
3,1001020400,"Autauga County, Alabama",1,4386,1722,0,0.0,0.00,0,0,...,904.0,4086.0,193.0,18.0,4.0,11.0,74.0,85.0,21.0,98.0
4,1001020500,"Autauga County, Alabama",1,10766,4082,0,181.0,1.68,0,0,...,1126.0,8666.0,1437.0,296.0,9.0,48.0,310.0,355.0,230.0,339.0

In [529]:
# drop census tract 
food_atlas = food_atlas.drop(['censusTract'], axis=1)

In [530]:
sum_cols = ['Population',
            'housingUnit', 
            'numGroupQuarter',
            'numLA_1_10',
            'numLA_half_10',
            'numLA_1_20',
            'numLILA_1_10',
            'numLILA_half_10',
            'numLILA_1_20',
            'numLA_half',
            'numLILA_half',
            'numLAKids_half',
            'numLASeniors_half',
            'numLAWhite_half',
            'numLABlack_half',
            'numLAAsian_half',
            'numLAnhopi_half',
            'numLANative_half',
            'numLAOtherRace_half',
            'numLALatine_half',
            'numLAHousingUnitNoVehicle_half',
            'numLAHousingUnitSNAP_half',
            'numLA_1',
            'numLILA_1',
            'numLAKids_1',
            'numLASeniors_1',
            'numLAWhite_1',
            'numLABlack_1',
            'numLAAsian_1',
            'numLAnhopi_1',
            'numLANative_1',
            'numLAOtherRace_1',
            'numLALatine_1',
            'numLAHousingUnitNoVehicle_1',
            'numLAHousingUnitSNAP_1',
            'numLA_10',
            'numLILA_10',
            'numLAKids_10',
            'numLASeniors_10',
            'numLAWhite_10',
            'numLABlack_10',
            'numLAAsian_10',
            'numLAnhopi_10',
            'numLANative_10',
            'numLAOtherRace_10',
            'numLALatine_10',
            'numLAHousingUnitNoVehicle_10',
            'numLAHousingUnitSNAP_10',
            'numLA_20',
            'numLILA_20',
            'numLAKids_20',
            'numLASeniors_20',
            'numLAWhite_20',
            'numLABlack_20',
            'numLAAsian_20',
            'numLAnhopi_20',
            'numLANative_20',
            'numLAOtherRace_20',
            'numLALatine_20',
            'numLAHousingUnitNoVehicle_20',
            'numLAHousingUnitSNAP_20',
            'numLI',
            'numKids',
            'numSeniors',
            'numWhite',
            'numBlack',
            'numAsian',
            'numNHOPI',
            'numNative',
            'numOtherRace',
            'numLatine',
            'numHousingUnitNoVehicle',
            'numHousingUnitSNAP']

In [531]:
food_atlas_columns = list(food_atlas.columns)

In [532]:
mean_cols = []
for item in food_atlas_columns:
    if item not in sum_cols:
        mean_cols.append(item)

In [533]:
mean_cols.remove('County, State')

In [534]:
agg_dict = {'mean':mean_cols, 'sum':sum_cols}

In [535]:
groupby_dict = {key:value for value, item in agg_dict.items() for key in item}

In [536]:
food_atlas_grouped = food_atlas.groupby('County, State', as_index=False).agg(groupby_dict)
food_atlas_grouped.head()

,"County, State",isUrban,isGroupQuarter67%,pctGroupQuarter,isLILA_1_10,isLILA_half_10,"isLILA_1_20,",isLILA_Vehicle,isLowVehicleAccess,isLowIncome,...,numSeniors,numWhite,numBlack,numAsian,numNHOPI,numNative,numOtherRace,numLatine,numHousingUnitNoVehicle,numHousingUnitSNAP
0,"Abbeville County, South Carolina",0.166667,0.000000,3.393333,0.333333,0.333333,0.166667,0.666667,0.666667,0.833333,...,4203.0,17691.0,7187.0,75.0,5.0,60.0,399.0,255.0,1014.0,1955.0
1,"Acadia Parish, Louisiana",0.500000,0.000000,1.651667,0.250000,0.500000,0.250000,0.250000,0.333333,0.666667,...,7886.0,49127.0,11175.0,137.0,6.0,163.0,1165.0,1060.0,1845.0,4359.0
2,"Accomack County, Virginia",0.000000,0.000000,0.922222,0.111111,0.111111,0.000000,0.777778,0.777778,0.888889,...,6336.0,21662.0,9303.0,183.0,40.0,135.0,1841.0,2850.0,1352.0,1920.0
3,"Ada County, Idaho",0.932203,0.016949,2.746780,0.016949,0.186441,0.016949,0.050847,0.186441,0.203390,...,41048.0,354347.0,4441.0,9407.0,861.0,2610.0,20699.0,27905.0,6431.0,12639.0
4,"Adair County, Iowa",0.000000,0.000000,1.740000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1644.0,7558.0,11.0,22.0,1.0,4.0,86.0,101.0,122.0,371.0

# Cleaning map the meal gap dataset

In [539]:
drop_columns = ['FIPS', 'Year', 'Rural-Urban Continuum Code (2023)', 'Census Region', 'Census Division']
meal_gap_2019 = meal_gap_2019.drop(drop_columns, axis=1)

In [540]:
meal_gap_2019.shape

(3142, 19)

In [541]:
meal_gap_2019_columns = ['State', 
                         'County, State',
                         'pctFoodInsecure',
                         'numFoodInsecure',
                         'pctBlackFoodInsecure',
                         'pctLatineFoodInsecure',
                         'pctWhiteFoodInsecure',
                         'SNAPthreshold',
                         'pctFIbelowSNAP',
                         'pctFIaboveSNAP',
                         'pctKidsFoodInsecure',
                         'numKidsFoodInsecure',
                         'pctKidsIncomeBelow185',
                         'pctKidsIncomeAbove185',
                         'costPerMeal',
                         'weeklyFoodBudget',
                         'weeklyBudgetFoodInsecureByPop',
                         'rangeRuralUrban',
                         'USstateRegion']

In [542]:
len(meal_gap_2019_columns)

19

In [543]:
meal_gap_2019 = meal_gap_2019.set_axis(meal_gap_2019_columns, axis=1)
meal_gap_2019.head()

,State,"County, State",pctFoodInsecure,numFoodInsecure,pctBlackFoodInsecure,pctLatineFoodInsecure,pctWhiteFoodInsecure,SNAPthreshold,pctFIbelowSNAP,pctFIaboveSNAP,pctKidsFoodInsecure,numKidsFoodInsecure,pctKidsIncomeBelow185,pctKidsIncomeAbove185,costPerMeal,weeklyFoodBudget,weeklyBudgetFoodInsecureByPop,rangeRuralUrban,USstateRegion
0,AL,"Autauga County, Alabama",15.7%,"8,670",26%,NaN,12%,130%,49%,51%,19.6%,"2,590",69%,31%,$3.00,$16.88,"$4,439,000",2.0,Southeast
5,AL,"Baldwin County, Alabama",13.4%,"28,590",26%,10%,11%,130%,39%,61%,14.4%,"6,680",79%,21%,$3.66,$20.63,"$17,895,000",3.0,Southeast
10,AL,"Barbour County, Alabama",20.7%,"5,250",34%,NaN,14%,130%,66%,34%,32.4%,"1,720",72%,28%,$3.11,$17.51,"$2,788,000",6.0,Southeast
15,AL,"Bibb County, Alabama",16.3%,"3,680",28%,NaN,14%,130%,48%,52%,21.8%,"1,010",89%,11%,$2.96,$16.68,"$1,861,000",1.0,Southeast
20,AL,"Blount County, Alabama",14.5%,"8,380",14%,11%,12%,130%,46%,54%,15.4%,"2,060",100%,0%,$3.04,$17.14,"$4,357,000",1.0,Southeast

In [544]:
meal_gap_2019['pctFoodInsecure'] = meal_gap_2019['pctFoodInsecure'].str[:-1].astype('float')
meal_gap_2019['pctBlackFoodInsecure'] = meal_gap_2019['pctBlackFoodInsecure'].str[:-1].astype('float')
meal_gap_2019['pctLatineFoodInsecure'] = meal_gap_2019['pctLatineFoodInsecure'].str[:-1].astype('float')
meal_gap_2019['pctWhiteFoodInsecure'] = meal_gap_2019['pctWhiteFoodInsecure'].str[:-1].astype('float')
meal_gap_2019['pctKidsFoodInsecure'] = meal_gap_2019['pctKidsFoodInsecure'].str[:-1].astype('float')


meal_gap_2019['SNAPthreshold'] = meal_gap_2019['SNAPthreshold'].str[:-1].astype('int')
meal_gap_2019['pctFIbelowSNAP'] = meal_gap_2019['pctFIbelowSNAP'].str[:-1].astype('int')
meal_gap_2019['pctFIaboveSNAP'] = meal_gap_2019['pctFIaboveSNAP'].str[:-1].astype('int')
meal_gap_2019['pctKidsIncomeBelow185'] = meal_gap_2019['pctKidsIncomeBelow185'].str[:-1].astype('int')
meal_gap_2019['pctKidsIncomeAbove185'] = meal_gap_2019['pctKidsIncomeAbove185'].str[:-1].astype('int')

meal_gap_2019['rangeRuralUrban'] = meal_gap_2019['rangeRuralUrban'].astype('int')

In [545]:
meal_gap_2019['numFoodInsecure'] = meal_gap_2019['numFoodInsecure'].apply(lambda x : int(x.replace(",", "")) if pd.notna(x) else x)
meal_gap_2019['numKidsFoodInsecure'] = meal_gap_2019['numKidsFoodInsecure'].apply(lambda x : int(x.replace(",", "")) if pd.notna(x) else x)

In [546]:
meal_gap_2019['costPerMeal'] = meal_gap_2019['costPerMeal'].str[1:].astype('float')
meal_gap_2019['weeklyFoodBudget'] = meal_gap_2019['weeklyFoodBudget'].str[1:].astype('float')

meal_gap_2019['weeklyBudgetFoodInsecureByPop'] = meal_gap_2019['weeklyBudgetFoodInsecureByPop'].str[1:].apply(lambda x : int(x.replace(",", "")) if pd.notna(x) else x)

In [547]:
meal_gap_2019.shape

(3142, 19)

In [550]:
meal_gap_2019.head()

,State,"County, State",pctFoodInsecure,numFoodInsecure,pctBlackFoodInsecure,pctLatineFoodInsecure,pctWhiteFoodInsecure,SNAPthreshold,pctFIbelowSNAP,pctFIaboveSNAP,pctKidsFoodInsecure,numKidsFoodInsecure,pctKidsIncomeBelow185,pctKidsIncomeAbove185,costPerMeal,weeklyFoodBudget,weeklyBudgetFoodInsecureByPop,rangeRuralUrban,USstateRegion
0,AL,"Autauga County, Alabama",15.7,8670,26.0,NaN,12.0,130,49,51,19.6,2590,69,31,3.00,16.88,4439000,2,Southeast
5,AL,"Baldwin County, Alabama",13.4,28590,26.0,10.0,11.0,130,39,61,14.4,6680,79,21,3.66,20.63,17895000,3,Southeast
10,AL,"Barbour County, Alabama",20.7,5250,34.0,NaN,14.0,130,66,34,32.4,1720,72,28,3.11,17.51,2788000,6,Southeast
15,AL,"Bibb County, Alabama",16.3,3680,28.0,NaN,14.0,130,48,52,21.8,1010,89,11,2.96,16.68,1861000,1,Southeast
20,AL,"Blount County, Alabama",14.5,8380,14.0,11.0,12.0,130,46,54,15.4,2060,100,0,3.04,17.14,4357000,1,Southeast

# Combining datasets

In [553]:
merged_data = food_atlas_grouped.merge(meal_gap_2019, on='County, State', how='left')
merged_data.head()

,"County, State",isUrban,isGroupQuarter67%,pctGroupQuarter,isLILA_1_10,isLILA_half_10,"isLILA_1_20,",isLILA_Vehicle,isLowVehicleAccess,isLowIncome,...,pctFIaboveSNAP,pctKidsFoodInsecure,numKidsFoodInsecure,pctKidsIncomeBelow185,pctKidsIncomeAbove185,costPerMeal,weeklyFoodBudget,weeklyBudgetFoodInsecureByPop,rangeRuralUrban,USstateRegion
0,"Abbeville County, South Carolina",0.166667,0.000000,3.393333,0.333333,0.333333,0.166667,0.666667,0.666667,0.833333,...,36.0,17.7,900.0,71.0,29.0,3.30,18.61,1739000.0,6.0,Southeast
1,"Acadia Parish, Louisiana",0.500000,0.000000,1.651667,0.250000,0.500000,0.250000,0.250000,0.333333,0.666667,...,38.0,26.0,4250.0,80.0,20.0,3.06,17.24,5956000.0,2.0,Southwest
2,"Accomack County, Virginia",0.000000,0.000000,0.922222,0.111111,0.111111,0.000000,0.777778,0.777778,0.888889,...,29.0,19.8,1370.0,67.0,33.0,3.02,17.00,1990000.0,8.0,Mid-Atlantic
3,"Ada County, Idaho",0.932203,0.016949,2.746780,0.016949,0.186441,0.016949,0.050847,0.186441,0.203390,...,57.0,8.7,9570.0,58.0,42.0,3.53,19.91,24382000.0,2.0,Western
4,"Adair County, Iowa",0.000000,0.000000,1.740000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,43.0,13.8,210.0,69.0,31.0,3.19,17.96,370000.0,8.0,Midwest

In [549]:
merged_data.shape

(3142, 163)

In [557]:
reindex = [145] + list(range(0, 145)) + list(range(146, 163))
merged_data = merged_data.iloc[:,reindex]

In [558]:
merged_data

,State,"County, State",isUrban,isGroupQuarter67%,pctGroupQuarter,isLILA_1_10,isLILA_half_10,"isLILA_1_20,",isLILA_Vehicle,isLowVehicleAccess,...,pctFIaboveSNAP,pctKidsFoodInsecure,numKidsFoodInsecure,pctKidsIncomeBelow185,pctKidsIncomeAbove185,costPerMeal,weeklyFoodBudget,weeklyBudgetFoodInsecureByPop,rangeRuralUrban,USstateRegion
0,SC,"Abbeville County, South Carolina",0.166667,0.000000,3.393333,0.333333,0.333333,0.166667,0.666667,0.666667,...,36.0,17.7,900.0,71.0,29.0,3.30,18.61,1739000.0,6.0,Southeast
1,LA,"Acadia Parish, Louisiana",0.500000,0.000000,1.651667,0.250000,0.500000,0.250000,0.250000,0.333333,...,38.0,26.0,4250.0,80.0,20.0,3.06,17.24,5956000.0,2.0,Southwest
2,VA,"Accomack County, Virginia",0.000000,0.000000,0.922222,0.111111,0.111111,0.000000,0.777778,0.777778,...,29.0,19.8,1370.0,67.0,33.0,3.02,17.00,1990000.0,8.0,Mid-Atlantic
3,ID,"Ada County, Idaho",0.932203,0.016949,2.746780,0.016949,0.186441,0.016949,0.050847,0.186441,...,57.0,8.7,9570.0,58.0,42.0,3.53,19.91,24382000.0,2.0,Western
4,IA,"Adair County, Iowa",0.000000,0.000000,1.740000,0.000000,0.000000,0.000000,0.000000,0.000000,...,43.0,13.8,210.0,69.0,31.0,3.19,17.96,370000.0,8.0,Midwest
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3137,AZ,"Yuma County, Arizona",0.792453,0.018868,4.159057,0.245283,0.547170,0.207547,0.037736,0.075472,...,14.0,29.5,15710.0,88.0,12.0,2.80,15.81,18314000.0,3.0,Southwest
3138,CO,"Yuma County, Colorado",0.000000,0.000000,2.045000,1.000000,1.000000,0.000000,0.000000,0.000000,...,14.0,13.6,360.0,94.0,6.0,2.99,16.83,561000.0,7.0,Mountain Plains
3139,TX,"Zapata County, Texas",0.666667,0.000000,0.250000,0.666667,1.000000,0.333333,0.333333,0.333333,...,9.0,28.0,1340.0,82.0,19.0,2.45,13.83,1166000.0,6.0,Southwest
3140,TX,"Zavala County, Texas",0.250000,0.000000,4.102500,0.750000,0.750000,0.500000,1.000000,1.000000,...,0.0,37.3,1330.0,97.0,4.0,2.33,13.15,1033000.0,7.0,Southwest
3141,SD,"Ziebach County, South Dakota",0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,...,26.0,32.1,270.0,94.0,6.0,3.26,18.39,357000.0,8.0,Mountain Plains

In [559]:
merged_data.to_csv('food_insecurity_merged.csv', index=False)